
# Only trigger on new tag matching a semantic versioning format
on:
  push:
    tags:
      - '*.*.*'


jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "On tag push"; env | sort
